# Generated by Django 4.1.3 on 2022-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reason',
            field=models.TextField(default='reason'),
            preserve_default=False,
        ),
    ]
